module Teste where 
import Bolha
import Quicksort
import Selection
import Insert
import Mergesort

l1=[1..2000]
l2=[2000,1999..1]
l3=l1++[0]
l4=[0]++l2
l5=l1++[0]++l2
l6=l2++[0]++l1
l7=l2++[0]++l2
x1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
x2=[20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]
x3=[11,12,13,14,15,16,17,18,19,20,1,2,3,4,5,6,7,8,9,10]
x4=[10,9,8,7,6,5,4,3,2,1,20,19,18,17,16,15,14,13,12,11]
x5=[11,12,13,14,15,5,4,3,2,1,16,17,18,19,20,10,9,8,7,6]
x6=[1,12,3,14,5,15,4,13,2,11,6,17,8,19,20,10,9,18,7,16]
x7=[20,8,2,11,13,3,7,18,14,4,16,10,15,1,9,17,19,12,5,6]

main :: IO ()
main = do
--  putStrLn $ show (bolhaOri l1)
--  putStrLn $ show (bolhaOri l2)
--  putStrLn $ show (bolhaOri l3)
--  putStrLn $ show (bolhaOri l4)
--  putStrLn $ show (bolhaOri l5)
--  putStrLn $ show (bolhaOri l6)
--  putStrLn $ show (bolhaOri l7)
--  putStrLn $ show (bolhaOri x1)
--  putStrLn $ show (bolhaOri x2)
--  putStrLn $ show (bolhaOri x3)
--  putStrLn $ show (bolhaOri x4)
--  putStrLn $ show (bolhaOri x5)
--  putStrLn $ show (bolhaOri x6)
--  putStrLn $ show (bolhaOri x7)
--  putStrLn $ show (bolhaVar1 l1)
--  putStrLn $ show (bolhaVar1 l2)
--  putStrLn $ show (bolhaVar1 l3)
--  putStrLn $ show (bolhaVar1 l4)
--  putStrLn $ show (bolhaVar1 l5)
--  putStrLn $ show (bolhaVar1 l6)
--  putStrLn $ show (bolhaVar1 l7)
--  putStrLn $ show (bolhaVar1 x1)
--  putStrLn $ show (bolhaVar1 x2)
--  putStrLn $ show (bolhaVar1 x3)
--  putStrLn $ show (bolhaVar1 x4)
--  putStrLn $ show (bolhaVar1 x5)
--  putStrLn $ show (bolhaVar1 x6)
--  putStrLn $ show (bolhaVar1 x7)
--  putStrLn $ show (bolhaVar2 l1)
--  putStrLn $ show (bolhaVar2 l2)
--  putStrLn $ show (bolhaVar2 l3)
--  putStrLn $ show (bolhaVar2 l4)
--  putStrLn $ show (bolhaVar2 l5)
--  putStrLn $ show (bolhaVar2 l6)
--  putStrLn $ show (bolhaVar2 l7)
--  putStrLn $ show (bolhaVar2 x1)
--  putStrLn $ show (bolhaVar2 x2)
--  putStrLn $ show (bolhaVar2 x3)
--  putStrLn $ show (bolhaVar2 x4)
--  putStrLn $ show (bolhaVar2 x5)
--  putStrLn $ show (bolhaVar2 x6)
--  putStrLn $ show (bolhaVar2 x7)
--  putStrLn $ show (quicksortOri l1)
--  putStrLn $ show (quicksortOri l2)
--  putStrLn $ show (quicksortOri l3)
--  putStrLn $ show (quicksortOri l4)
--  putStrLn $ show (quicksortOri l5)
--  putStrLn $ show (quicksortOri l6)
--  putStrLn $ show (quicksortOri l7)
--  putStrLn $ show (quicksortOri x1)
--  putStrLn $ show (quicksortOri x2)
--  putStrLn $ show (quicksortOri x3)
--  putStrLn $ show (quicksortOri x4)
--  putStrLn $ show (quicksortOri x5)
--  putStrLn $ show (quicksortOri x6)
--  putStrLn $ show (quicksortOri x7)
--  putStrLn $ show (quicksortVar1 l1)
--  putStrLn $ show (quicksortVar1 l2)
--  putStrLn $ show (quicksortVar1 l3)
--  putStrLn $ show (quicksortVar1 l4)
--  putStrLn $ show (quicksortVar1 l5)
--  putStrLn $ show (quicksortVar1 l6)
--  putStrLn $ show (quicksortVar1 l7)
--  putStrLn $ show (quicksortVar1 x1)
--  putStrLn $ show (quicksortVar1 x2)
--  putStrLn $ show (quicksortVar1 x3)
--  putStrLn $ show (quicksortVar1 x4)
--  putStrLn $ show (quicksortVar1 x5)
--  putStrLn $ show (quicksortVar1 x6)
--  putStrLn $ show (quicksortVar1 x7)
--  putStrLn $ show (quicksortVar2 l1)
--  putStrLn $ show (quicksortVar2 l2)
--  putStrLn $ show (quicksortVar2 l3)
--  putStrLn $ show (quicksortVar2 l4)
--  putStrLn $ show (quicksortVar2 l5)
--  putStrLn $ show (quicksortVar2 l6)
--  putStrLn $ show (quicksortVar2 l7)
--  putStrLn $ show (quicksortVar2 x1)
--  putStrLn $ show (quicksortVar2 x2)
--  putStrLn $ show (quicksortVar2 x3)
--  putStrLn $ show (quicksortVar2 x4)
--  putStrLn $ show (quicksortVar2 x5)
--  putStrLn $ show (quicksortVar2 x6)
--  putStrLn $ show (quicksortVar2 x7)
--  putStrLn $ show (selecaoOri l1)
--  putStrLn $ show (selecaoOri l2)
--  putStrLn $ show (selecaoOri l3)
--  putStrLn $ show (selecaoOri l4)
--  putStrLn $ show (selecaoOri l5)
--  putStrLn $ show (selecaoOri l6)
--  putStrLn $ show (selecaoOri l7)
--  putStrLn $ show (selecaoOri x1)
--  putStrLn $ show (selecaoOri x2)
--  putStrLn $ show (selecaoOri x3)
--  putStrLn $ show (selecaoOri x4)
--  putStrLn $ show (selecaoOri x5)
--  putStrLn $ show (selecaoOri x6)
--  putStrLn $ show (selecaoOri x7)
    putStrLn $ show (selecaoVar1 l1)
    putStrLn $ show (selecaoVar1 l2)
    putStrLn $ show (selecaoVar1 l3)
    putStrLn $ show (selecaoVar1 l4)
    putStrLn $ show (selecaoVar1 l5)
    putStrLn $ show (selecaoVar1 l6)
    putStrLn $ show (selecaoVar1 l7)
    putStrLn $ show (selecaoVar1 x1)
    putStrLn $ show (selecaoVar1 x2)
    putStrLn $ show (selecaoVar1 x3)
    putStrLn $ show (selecaoVar1 x4)
    putStrLn $ show (selecaoVar1 x5)
    putStrLn $ show (selecaoVar1 x6)
    putStrLn $ show (selecaoVar1 x7)
--  putStrLn $ show (selecaoVar2 l1)
--  putStrLn $ show (selecaoVar2 l2)
--  putStrLn $ show (selecaoVar2 l3)
--  putStrLn $ show (selecaoVar2 l4)
--  putStrLn $ show (selecaoVar2 l5)
--  putStrLn $ show (selecaoVar2 l6)
--  putStrLn $ show (selecaoVar2 l7)
--  putStrLn $ show (selecaoVar2 x1)
--  putStrLn $ show (selecaoVar2 x2)
--  putStrLn $ show (selecaoVar2 x3)
--  putStrLn $ show (selecaoVar2 x4)
--  putStrLn $ show (selecaoVar2 x5)
--  putStrLn $ show (selecaoVar2 x6)
--  putStrLn $ show (selecaoVar2 x7)
--  putStrLn $ show (insercaoOri l1)
--  putStrLn $ show (insercaoOri l2)
--  putStrLn $ show (insercaoOri l3)
--  putStrLn $ show (insercaoOri l4)
--  putStrLn $ show (insercaoOri l5)
--  putStrLn $ show (insercaoOri l6)
--  putStrLn $ show (insercaoOri l7)
--  putStrLn $ show (insercaoOri x1)
--  putStrLn $ show (insercaoOri x2)
--  putStrLn $ show (insercaoOri x3)
--  putStrLn $ show (insercaoOri x4)
--  putStrLn $ show (insercaoOri x5)
--  putStrLn $ show (insercaoOri x6)
--  putStrLn $ show (insercaoOri x7)
--  putStrLn $ show (insercaoFoldr l1)
--  putStrLn $ show (insercaoFoldr l2)
--  putStrLn $ show (insercaoFoldr l3)
--  putStrLn $ show (insercaoFoldr l4)
--  putStrLn $ show (insercaoFoldr l5)
--  putStrLn $ show (insercaoFoldr l6)
--  putStrLn $ show (insercaoFoldr l7)
--  putStrLn $ show (insercaoFoldr x1)
--  putStrLn $ show (insercaoFoldr x2)
--  putStrLn $ show (insercaoFoldr x3)
--  putStrLn $ show (insercaoFoldr x4)
--  putStrLn $ show (insercaoFoldr x5)
--  putStrLn $ show (insercaoFoldr x6)
--  putStrLn $ show (insercaoFoldr x7)
--  putStrLn $ show (quickSortOri l1)
--  putStrLn $ show (quickSortOri l2)
--  putStrLn $ show (quickSortOri l3)
--  putStrLn $ show (quickSortOri l4)
--  putStrLn $ show (quickSortOri l5)
--  putStrLn $ show (quickSortOri l6)
--  putStrLn $ show (quickSortOri l7)
--  putStrLn $ show (quickSortOri x1)
--  putStrLn $ show (quickSortOri x2)
--  putStrLn $ show (quickSortOri x3)
--  putStrLn $ show (quickSortOri x4)
--  putStrLn $ show (quickSortOri x5)
--  putStrLn $ show (quickSortOri x6)
--  putStrLn $ show (quickSortOri x7)
--  putStrLn $ show (quickSortVar1 l1)
--  putStrLn $ show (quickSortVar1 l2)
--  putStrLn $ show (quickSortVar1 l3)
--  putStrLn $ show (quickSortVar1 l4)
--  putStrLn $ show (quickSortVar1 l5)
--  putStrLn $ show (quickSortVar1 l6)
--  putStrLn $ show (quickSortVar1 l7)
--  putStrLn $ show (quickSortVar1 x1)
--  putStrLn $ show (quickSortVar1 x2)
--  putStrLn $ show (quickSortVar1 x3)
--  putStrLn $ show (quickSortVar1 x4)
--  putStrLn $ show (quickSortVar1 x5)
--  putStrLn $ show (quickSortVar1 x6)
--  putStrLn $ show (quickSortVar1 x7)
--  putStrLn $ show (quickSortVar2 l1)
--  putStrLn $ show (quickSortVar2 l2)
--  putStrLn $ show (quickSortVar2 l3)
--  putStrLn $ show (quickSortVar2 l4)
--  putStrLn $ show (quickSortVar2 l5)
--  putStrLn $ show (quickSortVar2 l6)
--  putStrLn $ show (quickSortVar2 l7)
--  putStrLn $ show (quickSortVar2 x1)
--  putStrLn $ show (quickSortVar2 x2)
--  putStrLn $ show (quickSortVar2 x3)
--  putStrLn $ show (quickSortVar2 x4)
--  putStrLn $ show (quickSortVar2 x5)
--  putStrLn $ show (quickSortVar2 x6)
--  putStrLn $ show (quickSortVar2 x7)
--  putStrLn $ show (mergesort l1)
--  putStrLn $ show (mergesort l2)
--  putStrLn $ show (mergesort l3)
--  putStrLn $ show (mergesort l4)
--  putStrLn $ show (mergesort l5)
--  putStrLn $ show (mergesort l6)
--  putStrLn $ show (mergesort l7)
--  putStrLn $ show (mergesort x1)
--  putStrLn $ show (mergesort x2)
--  putStrLn $ show (mergesort x3)
--  putStrLn $ show (mergesort x4)
--  putStrLn $ show (mergesort x5)
--  putStrLn $ show (mergesort x6)
--  putStrLn $ show (mergesort x7)